### ISSUE TITLE
Does the `query_hash` expire at some point ?

### ISSUE THREAD

**Issue by marcpicaud** [yc5/instagram-crawler#2]
Hey there,

Thanks for sharing this.

As I am not familiar with instagram caveats. I wonder if the query_hash expires at some point ?

Regards

**Comment by yc5** [comment]
Hi @marcpicaud , the ```query_hash``` would not expire unless Instagram update their database scheme or so.

Ref: https://stackoverflow.com/questions/54238696/what-is-query-hash-in-instagram

**Comment by marcpicaud** [comment]
Thanks for your reply @yc5 👍
